// Code generated by zeus-gen. DO NOT EDIT.
package errors

import (
	"net/http"
)

// 每个子项目特有的错误码定义，避免使用 0 ~ 19999，与公共库冲突
const (
	ECodeSuccessed ErrorCode = 0
	ECodeSystem ErrorCode = 10001
	ECodeSystemAPI ErrorCode = 10002

)

// ECodeMsg error message
var ECodeMsg = map[ErrorCode]string{
	ECodeSuccessed: "ok",
	ECodeSystem: "系统错误",
	ECodeSystemAPI: "系统api层错误",

}

// ECodeStatus http status code
var ECodeStatus = map[ErrorCode]int{
	ECodeSuccessed: http.StatusOK,
	ECodeSystem: http.StatusOK,
	ECodeSystemAPI: http.StatusOK,

}

