// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pubsub/proto/broker.proto

package broker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 公共数据结构
type Header struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             string            `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Source               string            `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Action               string            `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Customdata           map[string]string `protobuf:"bytes,5,rep,name=customdata,proto3" json:"customdata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_db12351e18f8fbbc, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Header) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Header) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Header) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Header) GetCustomdata() map[string]string {
	if m != nil {
		return m.Customdata
	}
	return nil
}

type Sample struct {
	Header               *Header      `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *Sample_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_db12351e18f8fbbc, []int{1}
}

func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (m *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(m, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Sample) GetBody() *Sample_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type Sample_Body struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sample_Body) Reset()         { *m = Sample_Body{} }
func (m *Sample_Body) String() string { return proto.CompactTextString(m) }
func (*Sample_Body) ProtoMessage()    {}
func (*Sample_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_db12351e18f8fbbc, []int{1, 0}
}

func (m *Sample_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample_Body.Unmarshal(m, b)
}
func (m *Sample_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample_Body.Marshal(b, m, deterministic)
}
func (m *Sample_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample_Body.Merge(m, src)
}
func (m *Sample_Body) XXX_Size() int {
	return xxx_messageInfo_Sample_Body.Size(m)
}
func (m *Sample_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Sample_Body proto.InternalMessageInfo

func (m *Sample_Body) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sample_Body) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RequestSample struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Finished             bool     `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSample) Reset()         { *m = RequestSample{} }
func (m *RequestSample) String() string { return proto.CompactTextString(m) }
func (*RequestSample) ProtoMessage()    {}
func (*RequestSample) Descriptor() ([]byte, []int) {
	return fileDescriptor_db12351e18f8fbbc, []int{2}
}

func (m *RequestSample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSample.Unmarshal(m, b)
}
func (m *RequestSample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSample.Marshal(b, m, deterministic)
}
func (m *RequestSample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSample.Merge(m, src)
}
func (m *RequestSample) XXX_Size() int {
	return xxx_messageInfo_RequestSample.Size(m)
}
func (m *RequestSample) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSample.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSample proto.InternalMessageInfo

func (m *RequestSample) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestSample) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RequestSample) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func init() {
	proto.RegisterType((*Header)(nil), "broker.Header")
	proto.RegisterMapType((map[string]string)(nil), "broker.Header.CustomdataEntry")
	proto.RegisterType((*Sample)(nil), "broker.Sample")
	proto.RegisterType((*Sample_Body)(nil), "broker.Sample.Body")
	proto.RegisterType((*RequestSample)(nil), "broker.RequestSample")
}

func init() { proto.RegisterFile("pubsub/proto/broker.proto", fileDescriptor_db12351e18f8fbbc) }

var fileDescriptor_db12351e18f8fbbc = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x49, 0x9a, 0xc6, 0x3a, 0xc5, 0x2a, 0xab, 0xc8, 0xda, 0x83, 0x94, 0x1e, 0xb4, 0x78,
	0x48, 0xa1, 0x5e, 0x44, 0xd0, 0x83, 0x22, 0x78, 0x5e, 0x8f, 0x9e, 0x36, 0xd9, 0xb1, 0x0d, 0x6d,
	0xb2, 0x75, 0x3f, 0x84, 0x3c, 0x80, 0x4f, 0xea, 0x8b, 0x48, 0x76, 0xb7, 0xc1, 0x8f, 0xdb, 0xfe,
	0x66, 0xe6, 0xbf, 0xf3, 0x9f, 0x19, 0x38, 0xdb, 0xda, 0x5c, 0xdb, 0x7c, 0xbe, 0x55, 0xd2, 0xc8,
	0x79, 0xae, 0xe4, 0x1a, 0x55, 0xe6, 0x80, 0xa4, 0x9e, 0xa6, 0x5f, 0x11, 0xa4, 0xcf, 0xc8, 0x05,
	0x2a, 0x32, 0x82, 0xb8, 0x14, 0x34, 0x9a, 0x44, 0xb3, 0x7d, 0x16, 0x97, 0x82, 0x8c, 0x61, 0x50,
	0x70, 0x83, 0x4b, 0xa9, 0x1a, 0x1a, 0xbb, 0x68, 0xc7, 0xe4, 0x14, 0x52, 0x2d, 0xad, 0x2a, 0x90,
	0xf6, 0x5c, 0x26, 0x50, 0x1b, 0xe7, 0x85, 0x29, 0x65, 0x4d, 0x13, 0x1f, 0xf7, 0x44, 0xee, 0x01,
	0x0a, 0xab, 0x8d, 0xac, 0x04, 0x37, 0x9c, 0xf6, 0x27, 0xbd, 0xd9, 0x70, 0x71, 0x9e, 0x05, 0x47,
	0xbe, 0x7f, 0xf6, 0xd8, 0x15, 0x3c, 0xd5, 0x46, 0x35, 0xec, 0x87, 0x62, 0x7c, 0x07, 0x87, 0x7f,
	0xd2, 0xe4, 0x08, 0x7a, 0x6b, 0x6c, 0x82, 0xdf, 0xf6, 0x49, 0x4e, 0xa0, 0xff, 0xc1, 0x37, 0x16,
	0x83, 0x5b, 0x0f, 0xb7, 0xf1, 0x4d, 0x34, 0xfd, 0x8c, 0x20, 0x7d, 0xe1, 0xd5, 0x76, 0x83, 0xe4,
	0x02, 0xd2, 0x95, 0xeb, 0xe7, 0x94, 0xc3, 0xc5, 0xe8, 0xb7, 0x0b, 0x16, 0xb2, 0xe4, 0x12, 0x92,
	0x5c, 0x0a, 0x3f, 0xf9, 0x70, 0x71, 0xbc, 0xab, 0xf2, 0xbf, 0x64, 0x0f, 0x52, 0x34, 0xcc, 0x15,
	0x8c, 0xaf, 0x20, 0x69, 0xe9, 0xdf, 0xfa, 0x08, 0x24, 0x35, 0xaf, 0x76, 0x66, 0xdc, 0x7b, 0xfa,
	0x0a, 0x07, 0x0c, 0xdf, 0x2d, 0x6a, 0x13, 0xdc, 0x50, 0xd8, 0xab, 0x50, 0x6b, 0xbe, 0xc4, 0xa0,
	0xdc, 0x61, 0x3b, 0x4c, 0x21, 0x6d, 0x6d, 0x9c, 0xbe, 0xcf, 0x3c, 0xb4, 0x37, 0x79, 0x2b, 0xeb,
	0x52, 0xaf, 0x50, 0xb8, 0xcd, 0x0f, 0x58, 0xc7, 0x79, 0xea, 0x2e, 0x7b, 0xfd, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xd4, 0x7d, 0x38, 0x0e, 0xf6, 0x01, 0x00, 0x00,
}
